[package]
name = "example_repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replman = { path = "../replman" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
