[package]
name = "example_repl"
version = "0.1.0"
edition = "2021"

[dependencies]
# replman = "0.1.0"
replman = { path = "../replman" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
